server {
  listen 80;
  server_name api.leaderty.solutions;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    proxy_pass http://api:3000;
  }
}

# server {
#   listen 443 ssl;
#   server_name tudominio.com www.tudominio.com;

#   ssl_certificate /etc/letsencrypt/live/tudominio.com/fullchain.pem;
#   ssl_certificate_key /etc/letsencrypt/live/tudominio.com/privkey.pem;

#   location / {
#     proxy_pass http://app:3000;
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#   }
# }