server {
  listen 80;
  server_name api.leaderty.solutions;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location /portfolio {
    proxy_pass http://portfolio:3000;
  }

  location / {
    proxy_pass http://api:3000;
  }
}

server {
  listen 443 ssl;
  server_name api.leaderty.solutions;

  ssl_certificate /etc/letsencrypt/live/api.leaderty.solutions/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.leaderty.solutions/privkey.pem;

  location /portfolio {
    proxy_pass http://portfolio:3000;
  }

  location / {
    proxy_pass http://api:3000;
  }
}